### ISSUE TITLE
Nginx controller complain about ratesvc and api

### ISSUE THREAD

**Issue by vtuson** [kubeapps/manifest#13]
after kubeapps up,  port 80 routes to the hub ui, however this fails to access the api endpoint, gets 404 (assume from the default backend)

looking at the logs of the ingress pod:
W1115 13:28:48.364416       8 controller.go:1041] service kubeapps/kubeapps-hub-api does not have any active endpoints
W1115 13:28:48.364458       8 controller.go:1041] service kubeapps/kubeapps-hub-ratesvc does not have any active endpoints
W

**Comment by prydonius** [comment]
what is the output of `kubectl -n kubeapps get po`?

**Comment by vtuson** [comment]
Pods are running fine,I can access the service directly
I deployed a busybox and curl the API and got the list of repos

I will try again with tomorrow's version of master and see if that helps

I am just doing a git pull on the installer repo and rebuilding a binary. Should I be doing something else?

**Comment by prydonius** [comment]
Ah if you're using the installer repo you probably aren't using the latest manifests in this repo. There's a static folder in the installer repo which contains the YAML manifest to install. You can run ./kubeapps.sh show in this repo to generate the YAML but you also need to create the secret for MongoDB.

@ngtuna we should make this process simpler, we could add a script to the installer repo to fetch and compile the latest manifest from this repo.
