### ISSUE TITLE
ci: use kubeapps/installer cmd rather than ./kubeapps.sh

### ISSUE THREAD

**Issue by prydonius** [kubeapps/manifest#19]
We should move away from testing with ./kubeapps.sh and use the real kubeapps CLI directly.

**Comment by anguslees** [comment]
:+1: This repo was only intended as a short-term stop-gap to parallelise work while the installer became functional (and the jsonnet code here is definitely not optimised for long-term maintenance).

Should we just delete this repo and work out some way to develop manifests within installer repo itself?

**Comment by prydonius** [comment]
@anguslees I agree that there isn't much gained from this being a separate repo and that we could just have jsonnet manifests in a `manifest` folder in the installer repo.

I'm a bit confused about whether the `kubeapps` CLI should be compiling jsonnet or simply installing a YAML manifest as it does today. I guess the simplest approach is to just use YAML, given we're bundling the YAML in the binary, but there are benefits to using jsonnet in that we can dynamically generate things such as the MongoDB password, for example.

**Comment by prydonius** [comment]
Turns out jsonnet doesn't generate random strings, so that invalidates the last point.

**Comment by ngtuna** [comment]
@prydonius Yes I made this PR to generate a random password within the script you submitted. PTAL https://github.com/kubeapps/kubeapps/pull/51
